server:
  port: 9002
spring:
  application:
    name: admin-server
  main:
    allow-bean-definition-overriding: true
  boot:
    admin:
      context-path: /admin
  cloud:
    discovery:
      client:
        simple:
          instances:
            registry-server:
              - uri: http://localhost:8761/
            config-server:              
              - uri: http://localhost:9001/
                metadata:
                  username: admin
                  password: admin
            api1:              
              - uri: http://localhost:8001/

  