eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
management:  endpoint:    health:      show-details: always   endpoints:    web:      exposure:        include:        - '*'
server:
  port: 8888
spring:
  application:
    name: gateway
  boot:
    admin:
      client:
        url:
        - http://localhost:9002/
        password: admin
        username: admin
        instance:
          prefer-ip: true 
  main:
    allow-bean-definition-overriding: true
    web-application-type: reactive
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/auth/realms/micro-formation
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: gateway
            client-secret: 5bb06c1a-3aae-474d-a26e-bef121fa31a9
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/auth/realms/micro-formation  
  cloud:
    discovery:
      enabled: true    
    gateway:
      default-filters:
        - TokenRelay
        - RemoveRequestHeader=Cookie
      routes:
        - id: product-resource-server
          uri: http://localhost:9191
          predicates:
            - Path=/product/**
        - id: api1
          uri: lb://api1
          predicates:
            - Path=/wagons/**
          filters:
            - TokenRelay
            - RemoveRequestHeader=Cookie
          
       