management:
  endpoint:
    health:
      show-details: always 
  endpoints:
    web:
      exposure:
        include:
        - '*'
eureka:
  client:
    register-with-eureka: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
server:
  port: 9001
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          search-locations: file:///C:/config/
  profiles:
    active: native
  security:
    user:
      name: admin
      password: admin

 
   

